---
- name: Setup server
  hosts: all
  remote_user: '{{ provision_username }}'
  vars_files:
    - vars.yaml
  roles:
    - { role: ssh, tags: ['ssh'] }
    - { role: firewall, tags: ['firewall'] }
    - { role: fail2ban, tags: ['fail2ban'] }
...