---
- name: Add firewall package
  package:
    name: nftables
    state: present

- name: Add firewall configuration
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    mode: '0644'

# The following three are required to ensure nftables has the necessary kernel modules loaded

# We're being liberal here, and adding more than we need.
# This comes at a speed penalty, but I figure it's negligible,
# especially compared to the time-consuming task of figuring out
# which ones are required or not.
- name: Which modules are required by nftables
  shell: |
    find /lib/modules/$(uname -r) -type f -regextype posix-egrep \
      -regex '.*/netfilter/nf[[:alnum:]_.]+$' \
      -printf %f\\n | \
      grep -Eo '^[[:alnum:]_]+'
  args:
    creates: /etc/modules-load.d/nftables.conf
  register: nftables_modules

- name: Add those modules to a load-list
  lineinfile:
    path: /etc/modules-load.d/nftables.conf
    line: "{{ item }}"
    state: present
    create: yes
  loop: "{{ nftables_modules.stdout_lines | default([]) }}"
  when: nftables_modules is success

- name: Load modules
  command: "modprobe {{ item }}"
  become: True
  loop: "{{ nftables_modules.stdout_lines | default([]) }}"
  when: nftables_modules is success
...