---
- name: Add firewall packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - nftables
    - conntrack
  register: installed_firewall

- name: Add firewall configuration
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0644'
  notify: reload nftables

- name: Add directory for additional firewall rulesets
  file:
    path: /etc/netfilter
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"

# The following three are required to ensure nftables has the necessary kernel modules loaded

# We're being liberal here, and adding more than we need.
# This comes at a speed penalty, but I figure it's negligible,
# especially compared to the time-consuming task of figuring out
# which ones are required or not.
- name: Which modules are required by nftables
  shell: |
    find /lib/modules/$(uname -r) -type f -regextype posix-egrep \
      -regex '.*/netfilter/nf[[:alnum:]_.]+$' \
      -printf %f\\n | \
      grep -Eo '^[[:alnum:]_]+'
  when: installed_firewall is changed
  register: nftables_modules

- name: Delete previous modules load list
  file:
    path: /etc/modules-load.d/nftables.conf
    state: absent
  when: installed_firewall is changed

- name: Add modules to a load list
  lineinfile:
    path: /etc/modules-load.d/nftables.conf
    line: "{{ item }}"
    state: present
    create: yes
  loop: "{{ nftables_modules.stdout_lines | default([]) }}"
  when: nftables_modules is changed
  register: firewall_modules

- name: Load modules
  command: "modprobe {{ item }}"
  become: True
  loop: "{{ nftables_modules.stdout_lines | default([]) }}"
  when: firewall_modules is changed

# From: https://github.com/Frzk/ansible-role-nftables/blob/master/tasks/main.yml
- name: Disable conflicting services
  become: yes
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  register: disable_service_result
  failed_when: (disable_service_result is failed)
               and ('Could not find the requested service' not in disable_service_result.msg)
  loop:
    - iptables

# Start and enable nftables services
- name: Start firewall
  service:
    name: "{{ item }}"
    state: started
  loop:
    - nftables

- name: Enable firewall on boot
  service:
    name: "{{ item }}"
    enabled: yes
  loop:
    - nftables
...